"use client";
import { cn } from "@/lib/utils";
export function Button({className,variant="primary",...p}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"secondary"|"danger"|"ghost"}){ const v={primary:"text-white",secondary:"border border-slate-300 bg-white text-slate-700 hover:bg-slate-50",danger:"bg-red-600 text-white hover:bg-red-700",ghost:"text-slate-600 hover:bg-slate-100"}[variant]; const style=variant==="primary"?{background:"var(--brand-primary)"}:undefined; return <button {...p} style={{...style,...p.style}} className={cn("focus-ring inline-flex h-10 items-center justify-center gap-2 rounded-lg px-4 text-sm font-semibold transition disabled:cursor-not-allowed disabled:opacity-50",v,className)}/> }
export function Input(p:React.InputHTMLAttributes<HTMLInputElement>){return <input {...p} className={cn("focus-ring h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm placeholder:text-slate-400",p.className)}/>}
export function Select(p:React.SelectHTMLAttributes<HTMLSelectElement>){return <select {...p} className={cn("focus-ring h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm",p.className)}/>}
export function Textarea(p:React.TextareaHTMLAttributes<HTMLTextAreaElement>){return <textarea {...p} className={cn("focus-ring min-h-24 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm",p.className)}/>}
export function Badge({children,tone="slate"}:{children:React.ReactNode;tone?:"slate"|"green"|"red"|"blue"|"amber"}){ const x={slate:"bg-slate-100 text-slate-700",green:"bg-emerald-50 text-emerald-700",red:"bg-red-50 text-red-700",blue:"bg-blue-50 text-blue-700",amber:"bg-amber-50 text-amber-700"}[tone]; return <span className={cn("inline-flex rounded-full px-2 py-0.5 text-xs font-medium",x)}>{children}</span> }
export function Card({children,className}:{children:React.ReactNode;className?:string}){return <div className={cn("cloud-card",className)}>{children}</div>}
export function PageHeader({title,description,actions}:{title:string;description?:string;actions?:React.ReactNode}){return <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-bold tracking-tight text-slate-950">{title}</h1>{description&&<p className="mt-1 text-sm text-slate-500">{description}</p>}</div>{actions&&<div>{actions}</div>}</div>}
